version: 2.1

jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build

  approve:
    
  delivery:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - <<: *install_node_modules
      - run:
          name: Install netlify-cli
          command: sudo npm install --unsafe-perm=true -g --silent netlify-cli
      - run: 
          name: Unlink App
          command: netlify unlink
      - run: 
          name: Define app
          command: netlify link --id $NETLIFY_SITE_ID_DELIVERY
      - run:
          name: Deploy to Netlify
          command: netlify deploy --dir=./build -p
          no_output_timeout: 30m

  deploy:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - <<: *install_node_modules
      - run:
          name: Install netlify-cli
          command: sudo npm install --unsafe-perm=true -g --silent netlify-cli
      - run: 
          name: Unlink App
          command: netlify unlink
      - run: 
          name: Define app
          command: netlify link --id $NETLIFY_SITE_ID_DEPLOY
      - run:
          name: Deploy to Netlify
          command: netlify deploy --dir=./build -p

workflows:
  version: 2
  build_and_deploy:
    jobs:      
      -prepare:
      - build:
          requires: 
            - prepare
          filters:
            branches:
              only: master
      
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
      
      - approve:
          type: approval
          requires:
            - build
          filters:
            branches:
              only: master
      
      - delivery:
          requires:
            - approve
          filters:
            branches:
              only: master
     