executors:
  node:
    docker:
      - image: circleci/node:14

aliases:
  install_node_modules: &install_node_modules
    run:
      name: Install dependencies
      command: npm install 

  save_cache: &save_cache
    run:
      name: Install dependencies
      command: npm uninstall typescript && npm i typescript@4.2.4

version: 2.1

jobs:
  build:
    executor: node
    steps:
      - checkout
      - <<: *install_node_modules
      - <<: *save_cache
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: ./
          paths:
            - build

  request-approve:

  delivery:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - <<: *install_node_modules
      - <<: *save_cache
      - run:
          name: Install netlify-cli
          command: sudo npm install --unsafe-perm=true -g --silent netlify-cli
      - run: 
          name: Unlink App
          command: netlify unlink
      - run: 
          name: Define app
          command: netlify link --id $NETLIFY_SITE_ID_DELIVERY
      - run:
          name: Deploy to Netlify
          command: netlify deploy --dir=./build -p

  deploy:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - <<: *install_node_modules
      - <<: *save_cache
      - run:
          name: Install netlify-cli
          command: sudo npm install --unsafe-perm=true -g --silent netlify-cli
      - run: 
          name: Unlink App
          command: netlify unlink
      - run: 
          name: Define app
          command: netlify link --id $NETLIFY_SITE_ID_DEPLOY
      - run:
          name: Deploy to Netlify
          command: netlify deploy --dir=./build -p

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: dat-feature
      - request-approve:
          type: approval
          requires:
            - build
      - delivery:
          requires:
            - request-approve
          filters:
            branches:
              only: dat-feature
     
